# -*- coding: utf-8 -*-
"""students performance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZ7Hy-IqP-MC6XIJoxL8ZhZr4yWsm0n0
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/StudentsPerformance.csv")

df

df.head()

df.tail()

df.info()

df.isnull().sum()

df.describe()

# Histogram of Marks
plt.figure(figsize=(8,5))
plt.hist(df["math score"], bins=10, edgecolor="black")

# Title and Labels
plt.title("Histogram of Math Scores")
plt.xlabel("Math Scores")
plt.ylabel("Number of Students")

plt.grid(True)
plt.show()

df["Marks"] = df["math score"] + df["reading score"] + df["writing score"]

# Histogram of Marks
plt.figure(figsize=(8,5))
plt.hist(df["reading score"], bins=10, edgecolor="black")

# Title and Labels
plt.title("Histogram of Math Scores")
plt.xlabel("reading score")
plt.ylabel("Number of Students")

plt.grid(True)
plt.show()

# Histogram of Marks
plt.figure(figsize=(8,5))
plt.hist(df["writing score"], bins=10, edgecolor="black")

# Title and Labels
plt.title("Histogram of Math Scores")
plt.xlabel("writing Scores")
plt.ylabel("Number of Students")

plt.grid(True)
plt.show()

import numpy as np

# Generate random study hours between 1 and 10
np.random.seed(42)   # Keeps the same values every run
df["Study Hours"] = np.random.randint(1, 11, size=len(df))

print(df.head())

study_hours = [2, 5, 3, 6, 8, 4, 7, 5, 9, 2]

# Repeat the list until it matches the dataset length
df["Study Hours"] = (study_hours * (len(df) // len(study_hours) + 1))[:len(df)]

X = df[["Study Hours"]]
y = df["Marks"]

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.scatter(df["Study Hours"], df["Marks"])

plt.title("Study Hours vs Marks")
plt.xlabel("Study Hours")
plt.ylabel("Marks")

plt.grid(True)

plt.show()

from sklearn.linear_model import LinearRegression
# X = Independent Variable
X = df[["Study Hours"]]

# y = Dependent Variable
y = df["Marks"]

# Create model
model = LinearRegression()

# Train the model
model.fit(X, y)

# Predict marks
predicted_marks = model.predict(X)

# Add predictions to dataframe
df["Predicted Marks"] = predicted_marks

# Display first 5 rows
print(df[["Study Hours", "Marks", "Predicted Marks"]].head())

print("Slope (Coefficient):", model.coef_[0])
print("Intercept:", model.intercept_)

# Example: Student studies 6 hours
new_hours = [[6]]

prediction = model.predict(new_hours)

print("Predicted Marks:", prediction[0])

